### ISSUE TITLE
Feature: Evolve invisibilization feature

### ISSUE THREAD

**Issue by malexander15** [TampaDevs/talent.tampa.dev#47]
#### Personas

As an Admin, I want a consistent mechanism to effectively lock/shadow-ban accounts in the event of spam/abuse or to force a user to contact support.

#### Problems with current feature:
- Businesses do not see a banner that their profile their profile is invisible but developers do. 
- Admins can mark developers and businesses as invisible, but there is no easy way to see/manage this aggregate
- There is no way to see/manage the invisible status of businesses
- Developers can un-invisibilize themselves

#### Feature changes
- [x] For any business or developer, if their accounts has been invisiblized, the should see a banner at the top of the page. 
- Developers already get this.([Here](https://github.com/TampaDevs/talent.tampa.dev/blob/main/app/components/developers/invisible_banner_component.rb).rb and [Here](https://github.com/TampaDevs/talent.tampa.dev/blob/main/app/components/developers/invisible_banner_component.html.erb).html.erb)
- [x] Update email copy on invisiblization to generically tell the user to contact the support team - jobs@tampadevs.com
- [x] As an admin, when managing a business/developer profile, there needs to be a switch that clearly displays whether a profile is already invisibilized or not.
- Alternatively, we could update the current button to toggle either highlighted or no slash open eye icon.
![image](https://github.com/TampaDevs/talent.tampa.dev/assets/16891186/4299d53e-7269-47d3-aee4-c5569241b935)
- [x] Change behavior/availability of Developer configurable invisibilize status
- Developers should not be able to edit this invisible status
- may need to adjust logic when a user is turned invisible in regards to the email notification

**Comment by chtzvt** [comment]
This feature has shipped. Well done!
